package com.murex.mxorbit.squadorchestrator.core.squad.execution.model;

import com.murex.mxorbit.squadorchestrator.core.squad.routing.SquadRoutingDecision;
import com.murex.mxorbit.squadorchestrator.core.workflow.client.WorkflowRunStatus;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.NonNull;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class SquadExecutionStatus {

	@NonNull
	private String squadId;

	@NonNull
	private WorkflowRunStatus overallStatus;

	@NonNull
	private List<SquadStepStatus> steps;

	@Builder.Default
	@NonNull
	@Schema(description = "Ordered routing decisions made during squad execution.")
	private List<SquadRoutingDecision> routingDecisions = new ArrayList<>();

	@Schema(description = "Output of the terminal step, populated once the squad run has COMPLETED.")
	private Map<String, Object> finalResult;

	@Schema(description = "Dynamic field labels for finalResult fields, generated by agents. Maps field key to display label.")
	private Map<String, String> finalResultFieldLabels;
}
